ALTER TABLE adgroups ADD COLUMN end_date VARCHAR(30);

ALTER TABLE adgroups ADD COLUMN end_date_dt TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE adgroups ADD COLUMN start_date VARCHAR(30);

ALTER TABLE adgroups ADD COLUMN start_date_dt TIMESTAMP WITHOUT TIME ZONE;
