"""empty message

Revision ID: 11352353f786
Revises: 1766adfa8fd
Create Date: 2017-12-01 13:13:52.398284

"""

# revision identifiers, used by Alembic.
revision = '11352353f786'
down_revision = '1766adfa8fd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.create_table('firefox_onboarding_events2_daily',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('addon_version', sa.String(length=64), nullable=False),
    sa.Column('bubble_state', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('current_tour_id', sa.String(length=64), nullable=False),
    sa.Column('logo_state', sa.String(length=16), nullable=False),
    sa.Column('notification_impression', sa.Integer(), nullable=False),
    sa.Column('notification_state', sa.String(length=16), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('parent_session_id', sa.String(length=64), nullable=False),
    sa.Column('root_session_id', sa.String(length=64), nullable=False),
    sa.Column('target_tour_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('tour_type', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('release_channel', sa.String(length=16), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    op.create_table('firefox_onboarding_sessions2_daily',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('addon_version', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('parent_session_id', sa.String(length=64), nullable=False),
    sa.Column('root_session_id', sa.String(length=64), nullable=False),
    sa.Column('session_begin', sa.BigInteger(), nullable=False),
    sa.Column('session_end', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('tour_type', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('release_channel', sa.String(length=16), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_table('firefox_onboarding_sessions2_daily')
    op.drop_table('firefox_onboarding_events2_daily')
    ### end Alembic commands ###
