"""empty message

Revision ID: 137eeadf84cb
Revises: 4c862338fcfa
Create Date: 2016-01-18 15:04:06.039453

"""

# revision identifiers, used by Alembic.
revision = '137eeadf84cb'
down_revision = '4c862338fcfa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiles', sa.Column('position_priority', sa.String(length=16), server_default=u'medium', nullable=True))
    op.get_bind().execute(text("UPDATE tiles SET position_priority='medium'"))
    op.alter_column('tiles', 'position_priority', nullable=False)
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiles', 'position_priority')
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

