"""empty message

Revision ID: 14abd58d84f5
Revises: 153663fadcdb
Create Date: 2017-10-25 11:21:49.594190

"""

# revision identifiers, used by Alembic.
revision = '14abd58d84f5'
down_revision = '153663fadcdb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'assa_sessions_daily', sa.Column('highlights_data_late_by_ms', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('is_preloaded', sa.Boolean(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('is_prerendered', sa.Boolean(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('rich_icon', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('screenshot', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('screenshot_with_icon', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('tippytop', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('topsites_data_late_by_ms', sa.Integer(), nullable=True))
    op.add_column(u'assa_impression_stats_daily', sa.Column('hour', sa.Integer(), nullable=True))
    op.add_column(u'assa_impression_stats_daily', sa.Column('minute', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'assa_sessions_daily', 'topsites_data_late_by_ms')
    op.drop_column(u'assa_sessions_daily', 'tippytop')
    op.drop_column(u'assa_sessions_daily', 'screenshot_with_icon')
    op.drop_column(u'assa_sessions_daily', 'screenshot')
    op.drop_column(u'assa_sessions_daily', 'rich_icon')
    op.drop_column(u'assa_sessions_daily', 'is_prerendered')
    op.drop_column(u'assa_sessions_daily', 'is_preloaded')
    op.drop_column(u'assa_sessions_daily', 'highlights_data_late_by_ms')
    op.drop_column(u'assa_impression_stats_daily', 'hour')
    op.drop_column(u'assa_impression_stats_daily', 'minute')
    ### end Alembic commands ###
