"""empty message

Revision ID: 153663fadcdb
Revises: 386a01af44c
Create Date: 2017-09-20 11:39:47.357032

"""

# revision identifiers, used by Alembic.
revision = '153663fadcdb'
down_revision = '386a01af44c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.create_table('ping_centre_main',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('shield_id', sa.String(length=256), nullable=False),
    sa.Column('release_channel', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    op.add_column(u'assa_events_daily', sa.Column('shield_id', sa.String(length=256), nullable=True))
    op.add_column(u'assa_impression_stats_daily', sa.Column('shield_id', sa.String(length=256), nullable=True))
    op.add_column(u'assa_masga_daily', sa.Column('shield_id', sa.String(length=256), nullable=True))
    op.add_column(u'assa_performance_daily', sa.Column('shield_id', sa.String(length=256), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('shield_id', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_table('ping_centre_main')
    op.drop_column(u'assa_sessions_daily', 'shield_id')
    op.drop_column(u'assa_performance_daily', 'shield_id')
    op.drop_column(u'assa_masga_daily', 'shield_id')
    op.drop_column(u'assa_impression_stats_daily', 'shield_id')
    op.drop_column(u'assa_events_daily', 'shield_id')
    ### end Alembic commands ###
