"""empty message

Revision ID: 1699070a0649
Revises: 4c862338fcfa
Create Date: 2015-12-01 10:59:44.827216

"""

# revision identifiers, used by Alembic.
revision = '1699070a0649'
down_revision = '4c862338fcfa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketer_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=216), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('bucketer_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('std_er', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bucketer_comscore',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Float(), nullable=False),
    sa.Column('users', sa.Float(), nullable=False),
    sa.Column('visits', sa.Float(), nullable=False),
    sa.Column('pages', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['bucketer_domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_table('bucketer_related',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['bucketer_domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_id'], ['bucketer_domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'related_id', 'source')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketer_related')
    op.drop_table('bucketer_comscore')
    op.drop_table('bucketer_model')
    op.drop_table('bucketer_domain')
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

