"""empty message

Revision ID: 1766adfa8fd
Revises: 14abd58d84f5
Create Date: 2017-11-10 10:27:23.686032

"""

# revision identifiers, used by Alembic.
revision = '1766adfa8fd'
down_revision = '14abd58d84f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'firefox_onboarding_events_daily', sa.Column('bubble_state', sa.String(length=64), nullable=True))
    op.add_column(u'firefox_onboarding_events_daily', sa.Column('notification_state', sa.String(length=64), nullable=True))
    op.add_column(u'firefox_onboarding_events_daily', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    op.add_column(u'firefox_onboarding_events_daily', sa.Column('tour_source', sa.String(length=64), nullable=True))
    op.add_column(u'firefox_onboarding_events_daily', sa.Column('tour_type', sa.String(length=64), nullable=True))
    op.add_column(u'firefox_onboarding_sessions_daily', sa.Column('tour_type', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'firefox_onboarding_sessions_daily', 'tour_type')
    op.drop_column(u'firefox_onboarding_events_daily', 'tour_type')
    op.drop_column(u'firefox_onboarding_events_daily', 'tour_source')
    op.drop_column(u'firefox_onboarding_events_daily', 'timestamp')
    op.drop_column(u'firefox_onboarding_events_daily', 'notification_state')
    op.drop_column(u'firefox_onboarding_events_daily', 'bubble_state')
    ### end Alembic commands ###

