"""empty message

Revision ID: 18b96423fcf0
Revises: 3473e3069558
Create Date: 2017-03-15 16:55:57.616928

"""

# revision identifiers, used by Alembic.
revision = '18b96423fcf0'
down_revision = '3473e3069558'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'activity_stream_events_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_masga', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_performance_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_stats_daily', sa.Column('topsites_screenshot', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_stats_daily', sa.Column('topsites_size', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_stats_daily', sa.Column('topsites_tippytop', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_stats_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'ss_event', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'ss_masga', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'ss_performance', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'ss_session', sa.Column('topsites_screenshot', sa.Integer(), nullable=True))
    op.add_column(u'ss_session', sa.Column('topsites_size', sa.Integer(), nullable=True))
    op.add_column(u'ss_session', sa.Column('topsites_tippytop', sa.Integer(), nullable=True))
    op.add_column(u'ss_session', sa.Column('user_prefs', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'ss_session', 'user_prefs')
    op.drop_column(u'ss_session', 'topsites_tippytop')
    op.drop_column(u'ss_session', 'topsites_size')
    op.drop_column(u'ss_session', 'topsites_screenshot')
    op.drop_column(u'ss_performance', 'user_prefs')
    op.drop_column(u'ss_masga', 'user_prefs')
    op.drop_column(u'ss_event', 'user_prefs')
    op.drop_column(u'activity_stream_stats_daily', 'user_prefs')
    op.drop_column(u'activity_stream_stats_daily', 'topsites_tippytop')
    op.drop_column(u'activity_stream_stats_daily', 'topsites_size')
    op.drop_column(u'activity_stream_stats_daily', 'topsites_screenshot')
    op.drop_column(u'activity_stream_performance_daily', 'user_prefs')
    op.drop_column(u'activity_stream_masga', 'user_prefs')
    op.drop_column(u'activity_stream_events_daily', 'user_prefs')
    ### end Alembic commands ###

