"""empty message

Revision ID: 19605520be19
Revises: 
Create Date: 2015-08-11 23:22:04.239007

"""

# revision identifiers, used by Alembic.
revision = '19605520be19'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('adgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('start_date', sa.String(length=30), nullable=True),
    sa.Column('end_date', sa.String(length=30), nullable=True),
    sa.Column('start_date_dt', sa.DateTime(), nullable=True),
    sa.Column('end_date_dt', sa.DateTime(), nullable=True),
    sa.Column('frequency_cap_daily', sa.Integer(), nullable=True),
    sa.Column('frequency_cap_total', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.String(length=255), nullable=True),
    sa.Column('check_inadjacency', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=True),
    sa.Column('scheduled_start_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adgroup_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adgroup_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('site', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adgroup_id'], ['adgroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('bg_color', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('adgroup_id', sa.Integer(), nullable=True),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('enhanced_image_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adgroup_id'], ['adgroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiles')
    op.drop_table('adgroup_sites')
    op.drop_table('distributions')
    op.drop_table('adgroups')
    op.drop_table('channels')
    ### end Alembic commands ###


def upgrade_stats():
    import os
    if "SPLICE_IGNORE_REDSHIFT" in os.environ:
        return
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_stats_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('ver', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False)
    )
    op.create_table('blacklisted_ips',
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False)
    )
    op.create_table('impression_stats_daily',
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pinned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored_link', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enhanced', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), server_default='false', nullable=False)
    )
    op.create_table('newtab_stats_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('newtabs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False)
    )
    op.create_table('site_stats_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pinned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored_link', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored', sa.Integer(), server_default='0', nullable=False)
    )
    ### end Alembic commands ###


def downgrade_stats():
    import os
    if "SPLICE_IGNORE_REDSHIFT" in os.environ:
        return
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_stats_daily')
    op.drop_table('newtab_stats_daily')
    op.drop_table('impression_stats_daily')
    op.drop_table('blacklisted_ips')
    op.drop_table('application_stats_daily')
    ### end Alembic commands ###

