"""empty message

Revision ID: 1e529bad1e38
Revises: 3364d1466fac
Create Date: 2015-05-20 17:42:07.580213

"""

# revision identifiers, used by Alembic.
revision = '1e529bad1e38'
down_revision = '3364d1466fac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'distributions', 'channels', ['channel_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distributions', type_='foreignkey')
    ### end Alembic commands ###
