"""empty message

Revision ID: 1f1804ed1cb
Revises: 19605520be19
Create Date: 2015-08-31 16:06:36.152182

"""

# revision identifiers, used by Alembic.
revision = '1f1804ed1cb'
down_revision = '19605520be19'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_adgroups_composite", "adgroups",
                                ["locale", "name", "channel_id", "start_date",
                                 "start_date_dt", "end_date", "end_date_dt",
                                 "frequency_cap_daily", "frequency_cap_total",
                                 "explanation", "check_inadjacency"])
    op.create_unique_constraint("uq_tiles_composite", "tiles",
                                ["target_url", "bg_color", "title", "type",
                                 "image_uri", "enhanced_image_uri"])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_adgroups_composite", "adgroups")
    op.drop_constraint("uq_tiles_composite", "tiles")
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

