"""empty message

Revision ID: 210703afa57c
Revises: 525c5cd32d85
Create Date: 2015-03-03 11:45:30.001695

"""

# revision identifiers, used by Alembic.
revision = '210703afa57c'
down_revision = '525c5cd32d85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('adgroups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(length=64), nullable=False),
                    sa.Column('locale', sa.String(length=14)),
                    sa.Column('country_code', sa.String(length=2)))

    op.create_table('adgroup_sites',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('site', sa.String(length=1024), nullable=False),
                    sa.Column('adgroup_id', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), default=True))

    op.add_column('tiles', sa.Column('adgroup_id', sa.Integer(), nullable=False))

    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('adgroups')
    op.drop_table('adgroup_sites')
    op.drop_column('tiles', 'adgroup_id')
    # end Alembic commands ###
