"""empty message

Revision ID: 232dce0d487f
Revises: 1e13ea64c8ed
Create Date: 2015-05-08 11:15:57.262064

"""

# revision identifiers, used by Alembic.
revision = '232dce0d487f'
down_revision = '1e13ea64c8ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # blacklisted_ips is an OLTP table
    op.create_table('blacklisted_ips',
                    sa.Column('ip', sa.String(length=16), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
                    sa.PrimaryKeyConstraint('ip'))

    # blacklist_stats_daily is an OLAP table
    op.create_table('blacklist_stats_daily',
                    sa.Column('ip', sa.String(length=16), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('pinned', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('sponsored_link', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('sponsored', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('newtabs', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_ips')
    op.drop_table('blacklist_stats_daily')
    ### end Alembic commands ###
