"""empty message

Revision ID: 2809b3efc07e
Revises: 90123954ee7
Create Date: 2017-08-10 13:22:15.823419

"""

# revision identifiers, used by Alembic.
revision = '2809b3efc07e'
down_revision = '90123954ee7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'assa_events_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'assa_masga_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'assa_performance_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('user_prefs', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'assa_sessions_daily', 'user_prefs')
    op.drop_column(u'assa_performance_daily', 'user_prefs')
    op.drop_column(u'assa_masga_daily', 'user_prefs')
    op.drop_column(u'assa_events_daily', 'user_prefs')
    ### end Alembic commands ###

