"""empty message

Revision ID: 2d3510d0a809
Revises: 49c8aa9350cd
Create Date: 2015-08-19 11:25:59.733407

"""

# revision identifiers, used by Alembic.
revision = '2d3510d0a809'
down_revision = '49c8aa9350cd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiles', sa.Column('attribution_period', sa.Integer(), nullable=True))
    op.add_column('tiles', sa.Column('attribution_url', sa.Text(), nullable=True))
    op.add_column('tiles', sa.Column('explanation', sa.String(length=255), nullable=True))
    op.drop_column('tiles', 'locale')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiles', sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.drop_column('tiles', 'explanation')
    op.drop_column('tiles', 'attribution_url')
    op.drop_column('tiles', 'attribution_period')
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

