"""empty message

Revision ID: 3364d1466fac
Revises: 4f7259e2a349
Create Date: 2015-05-13 15:43:22.249685

"""

# revision identifiers, used by Alembic.
revision = '3364d1466fac'
down_revision = '4f7259e2a349'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adgroups', sa.Column('check_blacklist', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adgroups', 'check_blacklist')
    ### end Alembic commands ###
