"""empty message

Revision ID: 3473e3069558
Revises: 4aada554f5e4
Create Date: 2017-02-14 16:08:06.575658

"""

# revision identifiers, used by Alembic.
revision = '3473e3069558'
down_revision = '4aada554f5e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.create_table('ping_centre_test_pilot',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('object', sa.String(length=64), nullable=True),
    sa.Column('client_time', sa.Integer(), nullable=False),
    sa.Column('variants', sa.String(length=64), nullable=True),
    sa.Column('addon_id', sa.String(length=64), nullable=False),
    sa.Column('addon_version', sa.String(length=64), nullable=False),
    sa.Column('firefox_version', sa.String(length=64), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('os_name', sa.String(length=64), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('raw', sa.String(length=4096), nullable=False)
    )
    op.create_table('activity_stream_mobile_events_daily',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('build', sa.String(length=64), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('action_position', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    op.create_table('activity_stream_mobile_stats_daily',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('build', sa.String(length=64), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('session_duration', sa.Integer(), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_table('ping_centre_test_pilot')
    op.drop_table('activity_stream_mobile_stats_daily')
    op.drop_table('activity_stream_mobile_events_daily')
    ### end Alembic commands ###

