"""empty message

Revision ID: 363dc755a823
Revises: 3cc07fb28766
Create Date: 2015-09-25 10:58:32.910319

"""

# revision identifiers, used by Alembic.
revision = '363dc755a823'
down_revision = '3cc07fb28766'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint('UQ_CAMPAIGN_ACCOUNT_ID_NAME', 'campaigns', ['account_id', 'name'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('UQ_CAMPAIGN_ACCOUNT_ID_NAME', 'campaigns', type_='unique')
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

