"""empty message

Revision ID: 363dc755a823
Revises: 3cc07fb28766
Create Date: 2015-09-25 10:58:32.910319

"""

# revision identifiers, used by Alembic.
revision = '363dc755a823'
down_revision = '3cc07fb28766'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adgroups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('adgroups', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.create_unique_constraint(None, 'adgroups', ['campaign_id', 'name', 'type'])
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'campaigns', ['account_id', 'name'])
    op.create_unique_constraint(None, 'tiles', ['adgroup_id', 'title', 'target_url', 'image_uri', 'enhanced_image_uri', 'type'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tiles', type_='unique')
    op.drop_constraint(None, 'campaigns', type_='unique')
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'adgroups', type_='unique')
    op.alter_column('adgroups', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('adgroups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

