"""empty message

Revision ID: 38617ef830fc
Revises: None
Create Date: 2014-09-08 11:38:09.435044

"""

# revision identifiers, used by Alembic.
revision = '38617ef830fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('bg_color', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('enhanced_image_uri', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unique_counts_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impression', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impression_stats_daily',
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pinned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored_link', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enhanced', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], )
    )
    op.create_table('unique_hlls',
    sa.Column('unique_counts_daily_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('value', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['unique_counts_daily_id'], ['unique_counts_daily.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unique_hlls')
    op.drop_table('impression_stats_daily')
    op.drop_table('unique_counts_daily')
    op.drop_table('tiles')
    ### end Alembic commands ###
