"""empty message

Revision ID: 386a01af44c
Revises: 49387f326d6a
Create Date: 2017-08-29 12:38:30.600279

"""

# revision identifiers, used by Alembic.
revision = '386a01af44c'
down_revision = '49387f326d6a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.create_table('firefox_onboarding_events_daily',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('addon_version', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('tour_id', sa.String(length=64), nullable=True),
    sa.Column('impression', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tour_source', sa.String(length=64), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    op.create_table('firefox_onboarding_sessions_daily',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('addon_version', sa.String(length=64), nullable=False),
    sa.Column('session_begin', sa.BigInteger(), nullable=False),
    sa.Column('session_end', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('impression', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tour_source', sa.String(length=64), nullable=False),
    sa.Column('receive_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=14), nullable=False)
    )
    op.add_column(u'assa_events_daily', sa.Column('release_channel', sa.String(length=16), nullable=True))
    op.add_column(u'assa_impression_stats_daily', sa.Column('release_channel', sa.String(length=16), nullable=True))
    op.add_column(u'assa_masga_daily', sa.Column('release_channel', sa.String(length=16), nullable=True))
    op.add_column(u'assa_performance_daily', sa.Column('release_channel', sa.String(length=16), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('release_channel', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'assa_sessions_daily', 'release_channel')
    op.drop_column(u'assa_performance_daily', 'release_channel')
    op.drop_column(u'assa_masga_daily', 'release_channel')
    op.drop_column(u'assa_impression_stats_daily', 'release_channel')
    op.drop_column(u'assa_events_daily', 'release_channel')
    op.drop_table('firefox_onboarding_sessions_daily')
    op.drop_table('firefox_onboarding_events_daily')
    ### end Alembic commands ###

