"""empty message

Revision ID: 39dbc740bd53
Revises: ad27dce9b87
Create Date: 2014-11-20 12:58:44.472555

"""

# revision identifiers, used by Alembic.
revision = '39dbc740bd53'
down_revision = 'ad27dce9b87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distributions', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distributions', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
