"""empty message

Revision ID: 3addd85ccbc9
Revises: 5614f34b9d8b
Create Date: 2016-11-02 10:31:38.849159

"""

# revision identifiers, used by Alembic.
revision = '3addd85ccbc9'
down_revision = '5614f34b9d8b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column('ss_event', sa.Column('tp_version', sa.String(length=64), nullable=True))
    op.add_column('ss_performance', sa.Column('tp_version', sa.String(length=64), nullable=True))
    op.add_column('ss_session', sa.Column('tp_version', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column('ss_session', 'tp_version')
    op.drop_column('ss_performance', 'tp_version')
    op.drop_column('ss_event', 'tp_version')
    ### end Alembic commands ###

