"""empty message

Revision ID: 3e454722b821
Revises: 11352353f786
Create Date: 2018-01-15 10:42:41.229053

"""

# revision identifiers, used by Alembic.
revision = '3e454722b821'
down_revision = '11352353f786'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'assa_impression_stats_daily', sa.Column('client_region', sa.String(length=5), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('client_region', sa.String(length=5), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('profile_creation_date', sa.Integer(), nullable=True))
    op.add_column(u'assa_sessions_daily', sa.Column('topsites_pinned', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'assa_sessions_daily', 'topsites_pinned')
    op.drop_column(u'assa_sessions_daily', 'profile_creation_date')
    op.drop_column(u'assa_sessions_daily', 'client_region')
    op.drop_column(u'assa_impression_stats_daily', 'client_region')
    ### end Alembic commands ###

