"""empty message

Revision ID: 410f1493e84b
Revises: 31e24c646a0a
Create Date: 2016-07-22 15:58:09.019548

"""

# revision identifiers, used by Alembic.
revision = '410f1493e84b'
down_revision = '31e24c646a0a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_stream_events_daily', sa.Column('recommendation_url', sa.String(length=255), nullable=True))
    op.add_column('activity_stream_events_daily', sa.Column('recommender_type', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_stream_events_daily', 'recommender_type')
    op.drop_column('activity_stream_events_daily', 'recommendation_url')
    ### end Alembic commands ###

