"""empty message

Revision ID: 44fe26926437
Revises: 171b15035012
Create Date: 2016-03-23 16:41:49.660096

"""

# revision identifiers, used by Alembic.
revision = '44fe26926437'
down_revision = '171b15035012'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_stream_stats_daily', sa.Column('date', sa.Date(), nullable=False))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_stream_stats_daily', 'date')
    ### end Alembic commands ###

