"""empty message

Revision ID: 47a9cfc38ebe
Revises: 332da7ae51f3
Create Date: 2018-12-13 16:44:49.828541

"""

# revision identifiers, used by Alembic.
revision = '47a9cfc38ebe'
down_revision = '332da7ae51f3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'assa_events_daily', sa.Column('profile_creation_date', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'assa_events_daily', 'profile_creation_date')
    ### end Alembic commands ###

