"""empty message

Revision ID: 4809e18091d6
Revises: None
Create Date: 2014-08-28 15:04:46.663330

"""

# revision identifiers, used by Alembic.
revision = '4809e18091d6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('bg_color', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('enhanced_image_uri', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiles_created_at'), 'tiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_tiles_locale'), 'tiles', ['locale'], unique=False)
    op.create_table('impression_stats_daily',
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pinned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored_link', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsored', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], )
    )
    op.create_index(op.f('ix_impression_stats_daily_browser'), 'impression_stats_daily', ['browser'], unique=False)
    op.create_index(op.f('ix_impression_stats_daily_country_code'), 'impression_stats_daily', ['country_code'], unique=False)
    op.create_index(op.f('ix_impression_stats_daily_date'), 'impression_stats_daily', ['date'], unique=False)
    op.create_index(op.f('ix_impression_stats_daily_device'), 'impression_stats_daily', ['device'], unique=False)
    op.create_index(op.f('ix_impression_stats_daily_locale'), 'impression_stats_daily', ['locale'], unique=False)
    op.create_index(op.f('ix_impression_stats_daily_os'), 'impression_stats_daily', ['os'], unique=False)
    op.create_index(op.f('ix_impression_stats_daily_version'), 'impression_stats_daily', ['version'], unique=False)
    op.create_table('unique_counts_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impression', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unique_counts_daily_country_code'), 'unique_counts_daily', ['country_code'], unique=False)
    op.create_index(op.f('ix_unique_counts_daily_date'), 'unique_counts_daily', ['date'], unique=False)
    op.create_index(op.f('ix_unique_counts_daily_locale'), 'unique_counts_daily', ['locale'], unique=False)
    op.create_table('unique_hlls',
    sa.Column('unique_counts_daily_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('value', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['unique_counts_daily_id'], ['unique_counts_daily.id'], )
    )
    op.create_index(op.f('ix_unique_hlls_index'), 'unique_hlls', ['index'], unique=False)
    op.create_index(op.f('ix_unique_hlls_value'), 'unique_hlls', ['value'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unique_hlls_value'), table_name='unique_hlls')
    op.drop_index(op.f('ix_unique_hlls_index'), table_name='unique_hlls')
    op.drop_table('unique_hlls')
    op.drop_index(op.f('ix_unique_counts_daily_locale'), table_name='unique_counts_daily')
    op.drop_index(op.f('ix_unique_counts_daily_date'), table_name='unique_counts_daily')
    op.drop_index(op.f('ix_unique_counts_daily_country_code'), table_name='unique_counts_daily')
    op.drop_table('unique_counts_daily')
    op.drop_index(op.f('ix_impression_stats_daily_version'), table_name='impression_stats_daily')
    op.drop_index(op.f('ix_impression_stats_daily_os'), table_name='impression_stats_daily')
    op.drop_index(op.f('ix_impression_stats_daily_locale'), table_name='impression_stats_daily')
    op.drop_index(op.f('ix_impression_stats_daily_device'), table_name='impression_stats_daily')
    op.drop_index(op.f('ix_impression_stats_daily_date'), table_name='impression_stats_daily')
    op.drop_index(op.f('ix_impression_stats_daily_country_code'), table_name='impression_stats_daily')
    op.drop_index(op.f('ix_impression_stats_daily_browser'), table_name='impression_stats_daily')
    op.drop_table('impression_stats_daily')
    op.drop_index(op.f('ix_tiles_locale'), table_name='tiles')
    op.drop_index(op.f('ix_tiles_created_at'), table_name='tiles')
    op.drop_table('tiles')
    ### end Alembic commands ###
