"""empty message

Revision ID: 49c8aa9350cd
Revises: 1cb25c33bb8c
Create Date: 2015-08-18 13:00:19.354957

"""

# revision identifiers, used by Alembic.
revision = '49c8aa9350cd'
down_revision = '1cb25c33bb8c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adgroups', sa.Column('category', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adgroups', 'category')
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

