"""empty message

Revision ID: 4cf6cb2e2309
Revises: 3e454722b821
Create Date: 2018-01-31 11:30:57.375544

"""

# revision identifiers, used by Alembic.
revision = '4cf6cb2e2309'
down_revision = '3e454722b821'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return

    op.drop_table('activity_stream_impression_daily')
    op.drop_table('ss_session')
    op.drop_table('ss_performance')
    op.drop_table('activity_stream_stats_daily')
    op.drop_table('ping_centre_test_pilot')
    op.drop_table('activity_stream_masga')
    op.drop_table('ss_masga')
    op.drop_table('ss_impression')
    op.drop_table('ss_event')
    op.drop_table('activity_stream_events_daily')
    op.drop_table('activity_stream_performance_daily')
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return

    op.create_table('activity_stream_performance_daily',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('metadata_source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('activity_stream_events_daily',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('page', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('action_position', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('recommendation_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recommender_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('highlight_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('share_provider', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('ss_event',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('shield_variant', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('page', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('action_position', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('recommendation_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recommender_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('highlight_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('share_provider', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tp_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('ss_impression',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('clicks', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('pinned', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('blocked', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('pocketed', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('blacklisted', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tp_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True)
    )
    op.create_table('ss_masga',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tp_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True)
    )
    op.create_table('activity_stream_masga',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('ping_centre_test_pilot',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('object', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('client_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variants', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('addon_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('firefox_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('os_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('os_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('raw', sa.VARCHAR(length=4096), autoincrement=False, nullable=False)
    )
    op.create_table('activity_stream_stats_daily',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('load_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('unload_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('max_scroll_depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('load_latency', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_bookmarks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_history_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('page', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('highlights_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_screenshot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_tippytop', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_lowresicon', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_pinned', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('ss_performance',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('shield_variant', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('metadata_source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tp_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('ss_session',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('load_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('page', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('unload_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('max_scroll_depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('load_latency', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_bookmarks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_history_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('shield_variant', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tp_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('highlights_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_screenshot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_tippytop', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_lowresicon', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topsites_pinned', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('activity_stream_impression_daily',
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('addon_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('clicks', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('pinned', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('blocked', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('pocketed', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('receive_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('blacklisted', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False),
    sa.Column('user_prefs', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###

