"""empty message

Revision ID: 556e52d3d14b
Revises: 18b96423fcf0
Create Date: 2017-04-12 09:29:08.857240

"""

# revision identifiers, used by Alembic.
revision = '556e52d3d14b'
down_revision = '18b96423fcf0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'activity_stream_stats_daily', sa.Column('topsites_lowresicon', sa.Integer(), nullable=True))
    op.add_column(u'activity_stream_stats_daily', sa.Column('topsites_pinned', sa.Integer(), nullable=True))
    op.add_column(u'ss_session', sa.Column('topsites_lowresicon', sa.Integer(), nullable=True))
    op.add_column(u'ss_session', sa.Column('topsites_pinned', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'ss_session', 'topsites_pinned')
    op.drop_column(u'ss_session', 'topsites_lowresicon')
    op.drop_column(u'activity_stream_stats_daily', 'topsites_pinned')
    op.drop_column(u'activity_stream_stats_daily', 'topsites_lowresicon')
    ### end Alembic commands ###

