"""empty message

Revision ID: 90123954ee7
Revises: 55df5c7c41fd
Create Date: 2017-07-26 16:04:04.834495

"""

# revision identifiers, used by Alembic.
revision = '90123954ee7'
down_revision = '55df5c7c41fd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.add_column(u'assa_sessions_daily', sa.Column('topsites_first_painted_ts', postgresql.DOUBLE_PRECISION(), nullable=True))
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    if os.environ.get("SPLICE_IGNORE_REDSHIFT", "") == "true":
        return
    op.drop_column(u'assa_sessions_daily', 'topsites_first_painted_ts')
    ### end Alembic commands ###

