"""empty message

Revision ID: bc666ca893d
Revises: 52913f05ec05
Create Date: 2014-12-15 12:46:31.530191

"""

# revision identifiers, used by Alembic.
revision = 'bc666ca893d'
down_revision = '52913f05ec05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributions', sa.Column('scheduled_start_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributions', 'scheduled_start_date')
    ### end Alembic commands ###
