"""empty message

Revision ID: d8d5541170a
Revises: 19605520be19
Create Date: 2015-09-03 15:51:24.538866

"""

# revision identifiers, used by Alembic.
revision = 'd8d5541170a'
down_revision = '19605520be19'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adgroup_categories',
    sa.Column('adgroup_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['adgroup_id'], ['adgroups.id'], ),
    sa.PrimaryKeyConstraint('adgroup_id', 'category')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adgroup_categories')
    ### end Alembic commands ###


def upgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_stats():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

