"""empty message

Revision ID: ec84b5b14c2
Revises: 4809e18091d6
Create Date: 2014-08-28 15:20:05.699790

"""

# revision identifiers, used by Alembic.
revision = 'ec84b5b14c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributions_created_at'), 'distributions', ['created_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distributions_created_at'), table_name='distributions')
    op.drop_table('distributions')
    ### end Alembic commands ###
