"""empty message

Revision ID: 1e13ea64c8ed
Revises: 210703afa57c
Create Date: 2015-04-24 17:10:07.310386

"""

# revision identifiers, used by Alembic.
revision = '1e13ea64c8ed'
down_revision = '210703afa57c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adgroup_sites', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('adgroup_sites', 'adgroup_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tiles', sa.Column('locale', sa.String(length=14), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiles', 'locale')
    op.alter_column('adgroup_sites', 'adgroup_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('adgroup_sites', 'active')
    ### end Alembic commands ###
