"""empty message

Revision ID: 232dce0d487f
Revises: 1e13ea64c8ed
Create Date: 2015-05-08 11:15:57.262064

"""

# revision identifiers, used by Alembic.
revision = '232dce0d487f'
down_revision = '1e13ea64c8ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # blacklisted_ips is an OLTP table
    op.create_table('blacklisted_ips',
                    sa.Column('ip', sa.String(length=64), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False))
    op.add_column('impression_stats_daily', sa.Column('blacklisted', sa.Boolean(), server_default='false'))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_ips')
    op.drop_column('impression_stats_daily', 'blacklisted')
    ### end Alembic commands ###
