"""empty message

Revision ID: 2732064ad441
Revises: 1e9d9b330237
Create Date: 2015-06-10 18:12:26.328127

"""

# revision identifiers, used by Alembic.
revision = '2732064ad441'
down_revision = '1e9d9b330237'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'adgroups', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adgroups', 'channels', ['channel_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adgroups', type_='foreignkey')
    op.drop_column(u'adgroups', 'channel_id')
    ### end Alembic commands ###
