"""empty message

Revision ID: 2d2603b0d445
Revises: 4d2de04038e9
Create Date: 2014-11-20 12:39:10.286831

"""

# revision identifiers, used by Alembic.
revision = '2d2603b0d445'
down_revision = '4d2de04038e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributions', sa.Column('channel_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributions', 'channel_id')
    ### end Alembic commands ###
