"""empty message

Revision ID: 37a805fca5aa
Revises: 1e529bad1e38
Create Date: 2015-05-21 10:50:23.345080

"""

# revision identifiers, used by Alembic.
revision = '37a805fca5aa'
down_revision = '1e529bad1e38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adgroups', sa.Column('explanation', sa.String(length=255), nullable=True))
    op.add_column('adgroups', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adgroups', 'name')
    op.drop_column('adgroups', 'explanation')
    ### end Alembic commands ###
