"""empty message

Revision ID: 4d2de04038e9
Revises: 4e412794c186
Create Date: 2014-11-20 11:04:47.421342

"""

# revision identifiers, used by Alembic.
revision = '4d2de04038e9'
down_revision = '4e412794c186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtab_stats_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('newtabs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=14), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False)
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    op.drop_table('newtab_stats_daily')
    ### end Alembic commands ###
