"""empty message

Revision ID: 4f7259e2a349
Revises: 232dce0d487f
Create Date: 2015-05-12 21:16:23.709773

"""

# revision identifiers, used by Alembic.
revision = '4f7259e2a349'
down_revision = '232dce0d487f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adgroups', sa.Column('frequency_cap_daily', sa.Integer(), nullable=True))
    op.add_column('adgroups', sa.Column('frequency_cap_total', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adgroups', 'frequency_cap_total')
    op.drop_column('adgroups', 'frequency_cap_daily')
    ### end Alembic commands ###
