"""empty message

Revision ID: 50908acd8263
Revises: 2732064ad441
Create Date: 2015-06-15 13:16:43.529165

"""

# revision identifiers, used by Alembic.
revision = '50908acd8263'
down_revision = '2732064ad441'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    ### end Alembic commands ###
