"""empty message

Revision ID: 52913f05ec05
Revises: 623ca22ebe7
Create Date: 2014-11-27 15:58:46.783446

"""

# revision identifiers, used by Alembic.
revision = '52913f05ec05'
down_revision = '623ca22ebe7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributions', sa.Column('deployed', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributions', 'deployed')
    ### end Alembic commands ###
