"""empty message

Revision ID: 623ca22ebe7
Revises: 39dbc740bd53
Create Date: 2014-11-21 15:42:23.271470

"""

# revision identifiers, used by Alembic.
revision = '623ca22ebe7'
down_revision = '39dbc740bd53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'created_at')
    ### end Alembic commands ###
